### PR TITLE
Added cp-apr algorithm in https://arxiv.org/pdf/1112.2414.pdf

### PR DESCRIPTION
**Pull request by brianholland**
Thanks also to @theosotr

### CODE REVIEW

**Comment by theosotr** [comment]
What's the need of another pull request? I suggest to give you access to my repo and push here, because I believe I have primary contributions here.

**Comment by brianholland** [comment]
Sure, we can proceed as you like.  If I understand correctly: I'd push to you, you'd give mnick a pull request on this one (cp-apr).  There were a couple of things I'd left comments on you your copy that I addressed in my version and also made defaults along the lines of the style already there, that's about it.

**Comment by theosotr** [comment]
@brianholland You have write access to https://github.com/theosotr/scikit-tensor

**Comment by brianholland** [comment]
Closed pull request since 1) failed CI and 2) to coordinate with @theosotr

**Pull request closed without merging**
